export const APP_CONSTANTS = {
  APP_NAME: 'GymFlow ERP',
  APP_VERSION: '1.0.0',
  DEFAULT_PAGE_SIZE: 10,
  PAGE_SIZE_OPTIONS: [10, 25, 50, 100],
  DATE_FORMAT: 'YYYY-MM-DD',
  TIME_FORMAT: 'HH:mm',
  DATETIME_FORMAT: 'YYYY-MM-DD HH:mm:ss',
  CURRENCY_SYMBOL: '$',
  CURRENCY_CODE: 'USD',
} as const;
