import { RoleType } from '../types/rbac.types';

export const ROLES: Record<RoleType, RoleType> = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  GYM_OWNER: 'GYM_OWNER',
  MANAGER: 'MANAGER',
  RECEPTIONIST: 'RECEPTIONIST',
  TRAINER: 'TRAINER',
  NUTRITIONIST: 'NUTRITIONIST',
  ACCOUNTANT: 'ACCOUNTANT',
  STORE_MANAGER: 'STORE_MANAGER',
  MAINTENANCE: 'MAINTENANCE',
  MEMBER: 'MEMBER',
};
