import { ITenantModels } from './tenant-database.manager.js';
import { logger } from '../core/logger/winston.logger.js';

export async function seedTenantDefaults(
  tenantModels: ITenantModels,
  tenantId: string,
  branchDoc: any,
  randomSuffix: string,
  currency: string = 'USD',
  gymName: string = 'GymFlow'
): Promise<void> {
  const branchId = branchDoc._id ? branchDoc._id.toString() : branchDoc.id || 'BR-HQ';
  const branchName = branchDoc.name || 'Main Facility';

  try {
    // 1. Predefined Security Roles & Permissions
    await Promise.all([
      tenantModels.Roles.create({
        tenantId,
        name: 'Gym Administrator / Owner',
        roleName: 'Gym Administrator / Owner',
        code: `ROL-ADMIN-${randomSuffix}`,
        roleKey: 'ADMIN',
        description: 'Master organizational control, financial records, staff provisioning, and billing oversight across all facility branches.',
        hierarchyTier: 1,
        isSystemRole: true,
        assignedUsersCount: 1,
        permissionModulesCount: 9,
        permissionsList: ['*'],
        permissions: ['*'],
        status: 'ACTIVE',
      }),
      tenantModels.Roles.create({
        tenantId,
        name: 'Branch General Manager',
        roleName: 'Branch General Manager',
        code: `ROL-MGR-${randomSuffix}`,
        roleKey: 'BRANCH_MANAGER',
        description: 'Branch-level operational oversight, shift management, attendance logs, and staff assignments.',
        hierarchyTier: 2,
        isSystemRole: true,
        assignedUsersCount: 0,
        permissionModulesCount: 6,
        permissionsList: [
          'gym:branches:view',
          'gym:departments:view',
          'gym:staff:view',
          'gym:staff:create',
          'members:members:view',
          'members:members:create',
          'members:members:update',
          'scheduling:classes:view',
          'scheduling:appointments:view',
          'fitness:workout-plans:view',
          'inventory:equipment:view',
          'analytics:attendance:view',
        ],
        permissions: [
          'gym:branches:view',
          'gym:departments:view',
          'gym:staff:view',
          'gym:staff:create',
          'members:members:view',
          'members:members:create',
          'members:members:update',
          'scheduling:classes:view',
          'scheduling:appointments:view',
          'fitness:workout-plans:view',
          'inventory:equipment:view',
          'analytics:attendance:view',
        ],
        status: 'ACTIVE',
      }),
      tenantModels.Roles.create({
        tenantId,
        name: 'Fitness Coach & Personal Trainer',
        roleName: 'Fitness Coach & Personal Trainer',
        code: `ROL-TRN-${randomSuffix}`,
        roleKey: 'TRAINER',
        description: 'Workout programming, personal training sessions, body assessments, and class instruction.',
        hierarchyTier: 3,
        isSystemRole: false,
        assignedUsersCount: 0,
        permissionModulesCount: 4,
        permissionsList: [
          'fitness:exercise-categories:view',
          'fitness:exercise-library:view',
          'fitness:workout-templates:view',
          'fitness:workout-plans:view',
          'fitness:workout-plans:create',
          'fitness:fitness-assessment:view',
          'members:members:view',
          'scheduling:appointments:view',
          'nutrition:diet-plans:view',
        ],
        permissions: [
          'fitness:exercise-categories:view',
          'fitness:exercise-library:view',
          'fitness:workout-templates:view',
          'fitness:workout-plans:view',
          'fitness:workout-plans:create',
          'fitness:fitness-assessment:view',
          'members:members:view',
          'scheduling:appointments:view',
          'nutrition:diet-plans:view',
        ],
        status: 'ACTIVE',
      }),
      tenantModels.Roles.create({
        tenantId,
        name: 'Front Desk & Member Concierge',
        roleName: 'Front Desk & Member Concierge',
        code: `ROL-REC-${randomSuffix}`,
        roleKey: 'RECEPTIONIST',
        description: 'Turnstile check-in, guest pass processing, member onboardings, and locker assignments.',
        hierarchyTier: 3,
        isSystemRole: false,
        assignedUsersCount: 0,
        permissionModulesCount: 3,
        permissionsList: [
          'members:members:view',
          'members:members:create',
          'members:members:update',
          'gym:branches:view',
          'scheduling:classes:view',
        ],
        permissions: [
          'members:members:view',
          'members:members:create',
          'members:members:update',
          'gym:branches:view',
          'scheduling:classes:view',
        ],
        status: 'ACTIVE',
      }),
      tenantModels.Roles.create({
        tenantId,
        name: 'Certified Nutritionist & Dietitian',
        roleName: 'Certified Nutritionist & Dietitian',
        code: `ROL-NUT-${randomSuffix}`,
        roleKey: 'NUTRITIONIST',
        description: 'Macronutrient meal planning, dietary consultations, hydration tracking, and supplement guidance.',
        hierarchyTier: 3,
        isSystemRole: false,
        assignedUsersCount: 0,
        permissionModulesCount: 3,
        permissionsList: [
          'nutrition:meal-library:view',
          'nutrition:meal-library:create',
          'nutrition:diet-plans:view',
          'nutrition:diet-plans:create',
          'nutrition:nutrition-tracking:view',
          'members:members:view',
          'fitness:workout-plans:view',
        ],
        permissions: [
          'nutrition:meal-library:view',
          'nutrition:meal-library:create',
          'nutrition:diet-plans:view',
          'nutrition:diet-plans:create',
          'nutrition:nutrition-tracking:view',
          'members:members:view',
          'fitness:workout-plans:view',
        ],
        status: 'ACTIVE',
      }),
      tenantModels.Roles.create({
        tenantId,
        name: 'Gym Member (Self-Service)',
        roleName: 'Gym Member (Self-Service)',
        code: `ROL-MBR-${randomSuffix}`,
        roleKey: 'MEMBER',
        description: 'Mobile app and portal access for workout logs, class bookings, subscription status, and billing history.',
        hierarchyTier: 4,
        isSystemRole: false,
        assignedUsersCount: 0,
        permissionModulesCount: 2,
        permissionsList: [
          'profile:view',
          'fitness:workout-plans:view',
          'nutrition:diet-plans:view',
          'scheduling:classes:view',
        ],
        permissions: [
          'profile:view',
          'fitness:workout-plans:view',
          'nutrition:diet-plans:view',
          'scheduling:classes:view',
        ],
        status: 'ACTIVE',
      }),
    ]).catch((err) => logger.warn('[TenantSeeder] Roles seed notice: ' + err.message));

    // 1.5 Predefined Granular Permissions Catalog
    await Promise.all([
      tenantModels.Permissions.create({
        tenantId,
        name: 'Sign GAAP Tax Invoices',
        permissionName: 'Sign GAAP Tax Invoices',
        code: 'gymflow.finance.invoices.sign',
        permissionCode: 'gymflow.finance.invoices.sign',
        moduleDomain: 'Finance & Billing',
        actionType: 'SIGN_OFF',
        description: 'Executive digital signature authority to certify tax invoices and reconcile payment settlements.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'CRITICAL',
        grantedRolesCount: 2,
        isSystemProtected: true,
        status: 'active',
      }),
      tenantModels.Permissions.create({
        tenantId,
        name: 'Override Turnstile IoT Gates',
        permissionName: 'Override Turnstile IoT Gates',
        code: 'gymflow.gym.turnstiles.override',
        permissionCode: 'gymflow.gym.turnstiles.override',
        moduleDomain: 'Gym Management',
        actionType: 'UPDATE',
        description: 'Emergency optical turnstile unlock and anti-tailgating sensor security override.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'HIGH',
        grantedRolesCount: 3,
        isSystemProtected: true,
        status: 'active',
      }),
      tenantModels.Permissions.create({
        tenantId,
        name: 'Freeze Member Contract',
        permissionName: 'Freeze Member Contract',
        code: 'gymflow.members.freeze.execute',
        permissionCode: 'gymflow.members.freeze.execute',
        moduleDomain: 'Member Management',
        actionType: 'UPDATE',
        description: 'Execute medical, travel, or military suspension freezes on active recurring contracts.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'MEDIUM',
        grantedRolesCount: 4,
        isSystemProtected: false,
        status: 'active',
      }),
      tenantModels.Permissions.create({
        tenantId,
        name: 'Approve Staff Payroll',
        permissionName: 'Approve Staff Payroll',
        code: 'gymflow.gym.staff.payroll',
        permissionCode: 'gymflow.gym.staff.payroll',
        moduleDomain: 'Gym Management',
        actionType: 'SIGN_OFF',
        description: 'Sign off on monthly coach commissions, hourly rates, and trainer payroll disbursements.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'HIGH',
        grantedRolesCount: 2,
        isSystemProtected: true,
        status: 'active',
      }),
      tenantModels.Permissions.create({
        tenantId,
        name: 'Publish Studio Schedule',
        permissionName: 'Publish Studio Schedule',
        code: 'gymflow.scheduling.classes.manage',
        permissionCode: 'gymflow.scheduling.classes.manage',
        moduleDomain: 'Fitness & Training',
        actionType: 'CREATE',
        description: 'Create and broadcast weekly instructor-led studio classes, capacity caps, and room reservations.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'LOW',
        grantedRolesCount: 3,
        isSystemProtected: false,
        status: 'active',
      }),
      tenantModels.Permissions.create({
        tenantId,
        name: 'Prescribe Clinical Diet Protocol',
        permissionName: 'Prescribe Clinical Diet Protocol',
        code: 'gymflow.nutrition.diet.prescribe',
        permissionCode: 'gymflow.nutrition.diet.prescribe',
        moduleDomain: 'Nutrition & Wellness',
        actionType: 'CREATE',
        description: 'Authorize personalized macronutrient targets, caloric allowances, and clinical dietary plans for members.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'MEDIUM',
        grantedRolesCount: 3,
        isSystemProtected: false,
        status: 'active',
      }),
      tenantModels.Permissions.create({
        tenantId,
        name: 'Provision Administrative Credentials',
        permissionName: 'Provision Administrative Credentials',
        code: 'gymflow.admin.users.manage',
        permissionCode: 'gymflow.admin.users.manage',
        moduleDomain: 'Administration & Security',
        actionType: 'CREATE',
        description: 'Generate employee IAM login credentials, reset two-factor authentication, and assign clearance tiers.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'CRITICAL',
        grantedRolesCount: 1,
        isSystemProtected: true,
        status: 'active',
      }),
      tenantModels.Permissions.create({
        tenantId,
        name: 'Export Compliance Logs',
        permissionName: 'Export Compliance Logs',
        code: 'gymflow.admin.audit.export',
        permissionCode: 'gymflow.admin.audit.export',
        moduleDomain: 'Administration & Security',
        actionType: 'EXPORT',
        description: 'Download CSV and PDF reports of access logs, role escalations, and financial audits.',
        iconAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        riskLevel: 'HIGH',
        grantedRolesCount: 2,
        isSystemProtected: false,
        status: 'active',
      }),
    ]).catch((err) => logger.warn('[TenantSeeder] Permissions seed notice: ' + err.message));

    // 2. Predefined Gym Departments
    await Promise.all([
      tenantModels.Departments.create({
        tenantId,
        name: 'Personal Training & Fitness',
        code: `DEP-FIT-${randomSuffix}`,
        category: 'FITNESS',
        description: 'Certified 1-on-1 personal trainers, strength coaches, and fitness assessment specialists.',
        color: '#10b981',
        branchId,
        branchName,
        status: 'active',
      }),
      tenantModels.Departments.create({
        tenantId,
        name: 'Front Desk & Member Operations',
        code: `DEP-OPS-${randomSuffix}`,
        category: 'OPERATIONS',
        description: 'Turnstile check-in, customer support, visitor passes, and retail supplement sales.',
        color: '#6366f1',
        branchId,
        branchName,
        status: 'active',
      }),
      tenantModels.Departments.create({
        tenantId,
        name: 'Group Fitness & Studio Classes',
        code: `DEP-STU-${randomSuffix}`,
        category: 'FITNESS',
        description: 'Instructor-led HIIT, spinning, yoga, Pilates, and high-energy group studio sessions.',
        color: '#f59e0b',
        branchId,
        branchName,
        status: 'active',
      }),
      tenantModels.Departments.create({
        tenantId,
        name: 'Clinical Nutrition & Dietetics',
        code: `DEP-NUT-${randomSuffix}`,
        category: 'NUTRITION',
        description: 'Personalized meal planning, macronutrient analysis, smoothie bar, and wellness consultations.',
        color: '#06b6d4',
        branchId,
        branchName,
        status: 'active',
      }),
      tenantModels.Departments.create({
        tenantId,
        name: 'Facility Housekeeping & Sanitization',
        code: `DEP-CLN-${randomSuffix}`,
        category: 'CLEANING',
        description: 'Gym floor sanitation, locker room hygiene, towel service, and janitorial maintenance.',
        color: '#8b5cf6',
        branchId,
        branchName,
        status: 'active',
      }),
      tenantModels.Departments.create({
        tenantId,
        name: 'Sales & Membership Advisory',
        code: `DEP-SAL-${randomSuffix}`,
        category: 'MANAGEMENT',
        description: 'New member acquisitions, corporate partnerships, lead conversions, and renewals.',
        color: '#ec4899',
        branchId,
        branchName,
        status: 'active',
      }),
      tenantModels.Departments.create({
        tenantId,
        name: 'Equipment Engineering & Maintenance',
        code: `DEP-MNT-${randomSuffix}`,
        category: 'FACILITY',
        description: 'Cardio machine servicing, cable replacements, HVAC airflow monitoring, and safety audits.',
        color: '#64748b',
        branchId,
        branchName,
        status: 'active',
      }),
    ]).catch((err) => logger.warn('[TenantSeeder] Departments seed notice: ' + err.message));

    // 3. Predefined Operational Shifts
    await Promise.all([
      tenantModels.Shifts.create({
        tenantId,
        name: 'Morning Dawn Opening Shift',
        code: `SHF-MRN-${randomSuffix}`,
        startTime: '06:00',
        endTime: '14:00',
        durationHours: 8,
        breakDurationMins: 45,
        minHeadcount: 2,
        daysOfWeek: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'],
        gracePeriodMins: 15,
        overtimeMultiplier: 1.5,
        color: '#f59e0b',
        branchId,
        branchName,
        status: 'active',
        description: 'Early morning facility opening, walkthrough checklist, equipment check, and rush check-ins.',
      }),
      tenantModels.Shifts.create({
        tenantId,
        name: 'Evening Prime Coaching Shift',
        code: `SHF-EVN-${randomSuffix}`,
        startTime: '14:00',
        endTime: '22:00',
        durationHours: 8,
        breakDurationMins: 60,
        minHeadcount: 3,
        daysOfWeek: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
        gracePeriodMins: 15,
        overtimeMultiplier: 1.5,
        color: '#6366f1',
        branchId,
        branchName,
        status: 'active',
        description: 'Peak afternoon and evening rush, group class management, and personal training slots.',
      }),
      tenantModels.Shifts.create({
        tenantId,
        name: 'Overnight / Security Shift',
        code: `SHF-NGT-${randomSuffix}`,
        startTime: '22:00',
        endTime: '06:00',
        durationHours: 8,
        breakDurationMins: 60,
        minHeadcount: 1,
        daysOfWeek: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
        gracePeriodMins: 15,
        overtimeMultiplier: 1.5,
        color: '#3b82f6',
        branchId,
        branchName,
        status: 'active',
        description: '24/7 keycard turnstile monitoring, deep cleaning, and overnight security access.',
      }),
      tenantModels.Shifts.create({
        tenantId,
        name: 'Weekend Split Operations',
        code: `SHF-WKD-${randomSuffix}`,
        startTime: '08:00',
        endTime: '16:00',
        durationHours: 8,
        breakDurationMins: 45,
        minHeadcount: 2,
        daysOfWeek: ['SATURDAY', 'SUNDAY'],
        gracePeriodMins: 15,
        overtimeMultiplier: 1.5,
        color: '#10b981',
        branchId,
        branchName,
        status: 'active',
        description: 'Weekend general facility coverage, introductory trial passes, and community workshops.',
      }),
    ]).catch((err) => logger.warn('[TenantSeeder] Shifts seed notice: ' + err.message));

    // 4. Predefined Holidays
    const currentYear = new Date().getFullYear();
    await Promise.all([
      tenantModels.Holidays.create({
        tenantId,
        name: "New Year's Day Celebration",
        code: `HOL-NYD-${randomSuffix}`,
        startDate: `${currentYear}-01-01`,
        endDate: `${currentYear}-01-01`,
        category: 'NATIONAL',
        operationalMode: 'REDUCED_HOURS',
        reducedHoursSchedule: '08:00 AM - 04:00 PM',
        classPolicy: 'RESCHEDULE',
        ptPolicy: 'PERMITTED',
        branchId,
        branchName,
        memberBroadcast: true,
        status: 'active',
        description: "Special reduced hours for New Year's Day. Group classes rescheduled; open gym permitted.",
      }),
      tenantModels.Holidays.create({
        tenantId,
        name: 'National Independence Day Observance',
        code: `HOL-NAT-${randomSuffix}`,
        startDate: `${currentYear}-07-04`,
        endDate: `${currentYear}-07-04`,
        category: 'NATIONAL',
        operationalMode: 'CLOSED',
        classPolicy: 'AUTO_CANCEL',
        ptPolicy: 'AUTO_CANCEL',
        branchId,
        branchName,
        memberBroadcast: true,
        status: 'active',
        description: 'Facility closed for National Independence Day. 24/7 RFID keyless access active for VIP tiers.',
      }),
      tenantModels.Holidays.create({
        tenantId,
        name: 'Annual Deep Clean & Equipment Servicing',
        code: `HOL-MNT-${randomSuffix}`,
        startDate: `${currentYear}-09-15`,
        endDate: `${currentYear}-09-16`,
        category: 'MAINTENANCE',
        operationalMode: 'CLOSED',
        classPolicy: 'AUTO_CANCEL',
        ptPolicy: 'AUTO_CANCEL',
        branchId,
        branchName,
        memberBroadcast: true,
        status: 'active',
        description: 'Scheduled semi-annual deep sanitation, sauna maintenance, and machine motor calibration.',
      }),
      tenantModels.Holidays.create({
        tenantId,
        name: 'Thanksgiving & Harvest Break',
        code: `HOL-THX-${randomSuffix}`,
        startDate: `${currentYear}-11-26`,
        endDate: `${currentYear}-11-27`,
        category: 'NATIONAL',
        operationalMode: 'REDUCED_HOURS',
        reducedHoursSchedule: '07:00 AM - 01:00 PM',
        classPolicy: 'RESCHEDULE',
        ptPolicy: 'PERMITTED',
        branchId,
        branchName,
        memberBroadcast: true,
        status: 'active',
        description: 'Morning holiday hours for Thanksgiving turkey workouts. Early facility shutdown at 1 PM.',
      }),
      tenantModels.Holidays.create({
        tenantId,
        name: 'Winter Festive & Christmas Holiday',
        code: `HOL-XMAS-${randomSuffix}`,
        startDate: `${currentYear}-12-25`,
        endDate: `${currentYear}-12-25`,
        category: 'NATIONAL',
        operationalMode: 'CLOSED',
        classPolicy: 'AUTO_CANCEL',
        ptPolicy: 'AUTO_CANCEL',
        branchId,
        branchName,
        memberBroadcast: true,
        status: 'active',
        description: 'Closed for Christmas celebration. Staff and coaches on paid company leave.',
      }),
    ]).catch((err) => logger.warn('[TenantSeeder] Holidays seed notice: ' + err.message));

    // 5. Predefined Fitness Sub-Module Items (Exercise Categories & Workout Templates)
    await Promise.all([
      tenantModels.ExerciseCategories.create({
        tenantId,
        name: 'Strength & Free Weights',
        code: `CAT-STR-${randomSuffix}`,
        description: 'Barbell, dumbbell, and plate-loaded exercises targeting hypertrophy and maximal force production.',
        status: 'active',
      }),
      tenantModels.ExerciseCategories.create({
        tenantId,
        name: 'Cardiovascular & Endurance',
        code: `CAT-CRD-${randomSuffix}`,
        description: 'Treadmills, rowers, assault air bikes, stair climbers, and aerobic capacity conditioning.',
        status: 'active',
      }),
      tenantModels.ExerciseCategories.create({
        tenantId,
        name: 'Functional Training & Core',
        code: `CAT-COR-${randomSuffix}`,
        description: 'Kettlebells, medicine balls, battle ropes, sled pushes, and core stabilization routines.',
        status: 'active',
      }),
      tenantModels.ExerciseCategories.create({
        tenantId,
        name: 'Flexibility & Joint Mobility',
        code: `CAT-MOB-${randomSuffix}`,
        description: 'Dynamic warmups, yoga sequences, myofascial release foam rolling, and hip/shoulder mobility.',
        status: 'active',
      }),
      tenantModels.WorkoutTemplates.create({
        tenantId,
        name: '4-Day Push / Pull / Legs Hypertrophy Split',
        code: `TMP-PPL-${randomSuffix}`,
        description: 'Gold-standard progressive overload template designed for intermediate and advanced muscular hypertrophy.',
        status: 'active',
      }),
      tenantModels.WorkoutTemplates.create({
        tenantId,
        name: 'High-Intensity Metabolic Fat Burner (HIIT)',
        code: `TMP-HIIT-${randomSuffix}`,
        description: 'Fast-paced 45-minute circuit alternating explosive cardio intervals with high-rep compound bodyweight drills.',
        status: 'active',
      }),
      tenantModels.WorkoutTemplates.create({
        tenantId,
        name: 'Beginner Full-Body Foundation & Posture',
        code: `TMP-BEG-${randomSuffix}`,
        description: '3-day full body regimen focusing on core motor patterns, squat mechanics, and posterior chain strength.',
        status: 'active',
      }),
    ]).catch((err) => logger.warn('[TenantSeeder] Fitness seed notice: ' + err.message));

    // 6. Predefined Nutrition Sub-Module Items (Meal Library & Diet Plans)
    await Promise.all([
      tenantModels.MealLibrary.create({
        tenantId,
        name: 'Grilled Atlantic Salmon with Quinoa & Steamed Asparagus',
        code: `MEL-SLM-${randomSuffix}`,
        description: 'High-protein, heart-healthy dinner loaded with Omega-3s. 580 kcal (48g Protein, 42g Carbs, 22g Healthy Fats).',
        status: 'active',
      }),
      tenantModels.MealLibrary.create({
        tenantId,
        name: 'Post-Workout Whey Isolate & Mixed Berry Protein Bowl',
        code: `MEL-WHE-${randomSuffix}`,
        description: 'Rapid glycogen replenish recovery bowl with rolled oats, blueberries, and whey protein. 440 kcal (36g Protein, 58g Carbs, 6g Fat).',
        status: 'active',
      }),
      tenantModels.MealLibrary.create({
        tenantId,
        name: 'Cage-Free Mediterranean Omelet with Avocado & Baby Spinach',
        code: `MEL-OML-${randomSuffix}`,
        description: 'Low-carb, high-satiety breakfast prepared with virgin olive oil, feta, and avocado. 410 kcal (26g Protein, 4g Carbs, 32g Fat).',
        status: 'active',
      }),
      tenantModels.DietPlans.create({
        tenantId,
        name: 'Clean Bulking & Hypertrophy Protocol (3,000 kcal)',
        code: `PLN-BLK-${randomSuffix}`,
        description: 'Structured 5-meal daily protocol designed to fuel intensive training and support lean muscle accretion with minimal fat gain.',
        status: 'active',
      }),
      tenantModels.DietPlans.create({
        tenantId,
        name: 'Rapid Fat Loss & Lean Shred Protocol (1,800 kcal)',
        code: `PLN-SHR-${randomSuffix}`,
        description: 'Controlled caloric deficit protocol featuring 2.2g/kg protein intake to preserve lean muscle tissue while maximizing fat oxidation.',
        status: 'active',
      }),
      tenantModels.DietPlans.create({
        tenantId,
        name: 'Athletic Performance & Maintenance (2,400 kcal)',
        code: `PLN-REC-${randomSuffix}`,
        description: 'Balanced 40% Carb / 30% Protein / 30% Fat fueling strategy for peak daily energy, workout recovery, and metabolic health.',
        status: 'active',
      }),
    ]).catch((err) => logger.warn('[TenantSeeder] Nutrition seed notice: ' + err.message));

    logger.info(`[TenantSeeder] Successfully seeded all default roles, departments, shifts, holidays, fitness, and nutrition records for tenant: ${tenantId}`);
  } catch (err: any) {
    logger.warn(`[TenantSeeder] Non-fatal notice during tenant seeding: ${err?.message || err}`);
  }
}
